Repository consenlabs/tokenlon-contracts, pull requests merged in 2023-08, with the labels that each got.

#272 replace with abi.encodeCall in UniAgent
  contracts/UniAgent.sol
Labels: v6-audit-fix

#273 refactor RFQ calculation with unchecked block
  contracts/RFQ.sol
Labels: v6-audit-fix

#275 Revert "cache array length"
  contracts/UniAgent.sol
  contracts/abstracts/AdminManagement.sol
Labels: v6-audit-fix

#274 fix RFQv2 order typehash
  contracts/utils/Offer.sol
  contracts/utils/RFQOrder.sol
Labels: v5

#276 refactor TokenCollector
  contracts/interfaces/IUniswapPermit2.sol
  contracts/utils/TokenCollector.sol
  test/forkMainnet/RFQv2.t.sol
  test/forkMainnet/TokenCollector.t.sol
  test/utils/Permit2.sol
  test/utils/Permit2Helper.sol
Labels: v5

#270 inlcude feeFactor in RFQv2 maker signature instead
  contracts/RFQv2.sol
  contracts/utils/Offer.sol
  contracts/utils/RFQOrder.sol
  test/forkMainnet/RFQv2.t.sol
Labels: v5

#271 adjust RFQv2 takerToken == ETH handling
  contracts/RFQv2.sol
  test/forkMainnet/RFQv2.t.sol
Labels: v5

#277 rollback and sync current deployment
  contracts/LimitOrder.sol
  contracts/PermanentStorage.sol
  contracts/RFQ.sol
  contracts/Spender.sol
  contracts/UserProxy.sol
  contracts/interfaces/IPermanentStorage.sol
  contracts/interfaces/ISpender.sol
  contracts/utils/PSStorage.sol
  contracts/utils/UserProxyStorage.sol
  poc/L2Deposit.sol
  poc/L2Deposit/Deposit.t.sol
  poc/L2Deposit/Optimism.t.sol
  poc/L2Deposit/Setup.t.sol
  poc/L2Deposit/SetupTest.t.sol
  poc/L2Deposit/Signing.t.sol
  test/PermanentStorage.t.sol
  test/Spender.t.sol
  test/UserProxy.t.sol
  test/utils/StrategySharedSetup.sol
Labels: v5

#284 fix GenericSwapData type string: remove redundant abi.encodePacked pr…
  contracts/libraries/GenericSwapData.sol
Labels: v6

#285 mv v6.0.0 audit report
  audits/Tokenlon-v6.0.0-Smart-Contract-Audit-Report-Decurity.pdf
Labels: v6

#286 Signature sanity check
  foundry.toml
  test/Signing.t.sol
  test/forkMainnet/GenericSwap.t.sol
  test/forkMainnet/LimitOrderSwap/CoordinatedTaker.t.sol
  test/forkMainnet/LimitOrderSwap/Fill.t.sol
  test/forkMainnet/LimitOrderSwap/GroupFill.t.sol
  test/forkMainnet/LimitOrderSwap/Setup.t.sol
  test/forkMainnet/RFQ.t.sol
  test/forkMainnet/SmartOrderStrategy/IntegrationV6.t.sol
  test/utils/SigHelper.sol
  test/utils/payload/allowFill.json
  test/utils/payload/genericSwapData.json
  test/utils/payload/limitOrder.json
  test/utils/payload/rfqOffer.json
  test/utils/payload/rfqTx.json
Labels: v6

#289 refactor RFQv2 test
  test/forkMainnet/RFQv2.t.sol
Labels: v5

#287 update dep and linter
  .solhint.json
  contracts/AMMStrategy.sol
  contracts/AllowanceTarget.sol
  contracts/LimitOrderSwap.sol
  contracts/RFQ.sol
  contracts/SmartOrderStrategy.sol
  contracts/UniAgent.sol
  contracts/UniswapStrategy.sol
  contracts/abstracts/TokenCollector.sol
  contracts/interfaces/IAMMStrategy.sol
  contracts/interfaces/IAllowanceTarget.sol
  contracts/interfaces/ICurveFi.sol
  contracts/interfaces/ICurveFiV2.sol
  contracts/interfaces/ILimitOrderSwap.sol
  contracts/interfaces/IRFQ.sol
  contracts/interfaces/IStrategy.sol
  contracts/interfaces/IUniAgent.sol
  contracts/interfaces/IUniswapPermit2.sol
  contracts/interfaces/IUniswapRouterV2.sol
  contracts/interfaces/IUniswapUniversalRouter.sol
  contracts/interfaces/IUniswapV3SwapCallback.sol
  contracts/interfaces/IUniswapV3SwapRouter.sol
  contracts/interfaces/IWETH.sol
  contracts/libraries/Asset.sol
  contracts/libraries/MerkleProof.sol
  contracts/libraries/SignatureValidator.sol
  contracts/libraries/UniswapV2.sol
  contracts/libraries/UniswapV3.sol
  package.json
  test/forkMainnet/AMMStrategy.t.sol
  test/forkMainnet/TokenCollector.t.sol
  test/libraries/SignatureValidator.t.sol
  test/mocks/MockDeflationaryERC20.sol
  test/mocks/MockERC1271Wallet.sol
  test/mocks/MockERC20.sol
  test/mocks/MockERC20Permit.sol
  test/mocks/MockLimitOrderTaker.sol
  test/mocks/MockNoReturnERC20.sol
  test/mocks/MockNoRevertERC20.sol
  test/mocks/MockStrategy.sol
  test/mocks/MockWETH.sol
  test/utils/BalanceUtil.sol
  test/utils/Permit2Helper.sol
  test/utils/SigHelper.sol
  yarn.lock
Labels: v6

#290 move UniswapCommands path
  test/forkMainnet/AMMStrategy.t.sol
  test/forkMainnet/UniAgent/Universal.t.sol
  test/utils/UniswapCommands.sol
Labels: v6
